### PR TITLE
Me being completely stupid and not testing 2 or more recipes after having added id + new mod support

### PR DESCRIPTION
**Pull request by MundM2007**
- fixed the entire code breaking when not provided with the id
- improved Readme
- added support for Ex Nihilo + Ex Compressum

### CODE REVIEW

**Comment by Gcat101** [comment]
lmao

**Comment by MundM2007** [comment]
Also update the Kubejs wiki page of KJSPKG with the new format:
global.mrt.powah.energizing(event, "minecraft:gold_ingot", ["minecraft:stick", "minecraft:iron_ingot"], 1000);

**Comment by Gcat101** [comment]
yeah will do that thx for reminding

**Comment by Gcat101** [comment]
done

**Pull request merged**
